---
# tasks file for httpd
- name: update yum
  yum:
    name: "*"
    state: latest
- name: install httpd package
  yum:
    name: "{{ httpd_package }}"
    state: present
- name: start and enable httpd
  service:
    name: "{{ httpd_package }}"
    state: started
    enabled: true
- name: enable port 80 for httpd
  ansible.posix.firewalld:
    port: 80/tcp
    state: enabled
    permanent: true
    immediate: true
  when: firewalld_enabled